<footer class="site-footer">
  <div class="footer-container">
    <p>
      Contact us: thongnguyenvndn@gmail.com</a> | Phone: 0799300909
    </p>

    <p>
      Head Office: Level 5, ABC Building, 123 Le Duan Street, Da Nang, Vietnam
    </p>

    <p>
      Follow us:
      <a href="https://github.com/NguyenNThong/project1">GitHub</a>
    </p>

    <p>
      Project Management: <a href="https://hoangphuchai19102006.atlassian.net/jira/software/projects/PA/summary">Jira Project</a>
    </p>

    <p>
      Manager UI: <a href="login.php">Manage</a>
    </p>

    <p>
      Enhancements: <a href="enhancements.php">Enhancements</a>
    </p>

    <p>
      &copy; <span>2025</span> Company XXX. All rights reserved.
    </p>
  </div>
</footer>